import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
// @ts-ignore: Allow side-effect CSS import without type declarations
import "./globals.css";
// @ts-ignore
import "aos/dist/aos.css";

import { AuthProvider } from "@/context/AuthContext";
import { CartProvider } from "@/context/CartContext";
import Navbar from "@/pages/Home/Navbar/Navbar";
import AOSProvider from "@/providers/AosProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <CartProvider>
            <AOSProvider>
              <Navbar />
              {children}
            </AOSProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}